-- Only ALTER TABLE statements (tables already exist)
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "legal_business_name" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "brand_name" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "registration_number" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "saleor_page_slug" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "eori_number" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "phone_number" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "website_url" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "street" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "city" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "postal_code" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "country_code" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "latitude" double precision;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "longitude" double precision;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "geocoded_at" timestamp;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "shipping_countries" jsonb DEFAULT '[]'::jsonb;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "two_factor_secret" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "two_factor_enabled" boolean DEFAULT false NOT NULL;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "reset_token" text;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "reset_token_expiry" timestamp;
ALTER TABLE "vendor_applications" ADD COLUMN IF NOT EXISTS "legal_business_name" text;
ALTER TABLE "vendor_applications" ADD COLUMN IF NOT EXISTS "brand_name" text;
ALTER TABLE "vendor_applications" ADD COLUMN IF NOT EXISTS "registration_number" text;
ALTER TABLE "vendor_applications" ADD COLUMN IF NOT EXISTS "eori_number" text;
ALTER TABLE "vendor_applications" ADD COLUMN IF NOT EXISTS "phone_number" text;
ALTER TABLE "vendor_applications" ADD COLUMN IF NOT EXISTS "website_url" text;
ALTER TABLE "vendor_applications" ADD COLUMN IF NOT EXISTS "street" text;
ALTER TABLE "vendor_applications" ADD COLUMN IF NOT EXISTS "city" text;
ALTER TABLE "vendor_applications" ADD COLUMN IF NOT EXISTS "postal_code" text;
ALTER TABLE "vendor_applications" ADD COLUMN IF NOT EXISTS "country_code" text;
-- Drop deprecated columns
ALTER TABLE "users" DROP COLUMN IF EXISTS "warehouse_address";
ALTER TABLE "vendor_applications" DROP COLUMN IF EXISTS "country";
ALTER TABLE "vendor_applications" DROP COLUMN IF EXISTS "warehouse_address";